global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rustway-gateway'
    static_configs:
      - targets: ['localhost:8081']
    metrics_path: '/metrics'
    scrape_interval: 5s
    
  - job_name: 'rustway-gateway-docker'
    static_configs:
      - targets: ['rustway:8081']
    metrics_path: '/metrics'
    scrape_interval: 5s
